# Generated by Django 5.2.17 on 2026-09-13 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('unidade', models.CharField(choices=[('Kg', 'Kg'), ('L', 'L'), ('un', 'un')], max_length=2, verbose_name='Unidade')),
                ('meta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Meta de reposição')),
                ('estoque_inicial', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estoque inicial')),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Consumo do período')),
                ('validade', models.DateField(verbose_name='Validade')),
                ('acabou_antes_fim_mes', models.BooleanField(default=False, verbose_name='Acabou antes do fim do mês')),
            ],
            options={
                'ordering': ['nome', 'pk'],
            },
        ),
    ]
